### ISSUE TITLE
Add support to use http for IdentityServer endpoint (for local environment)

### ISSUE THREAD

**Issue by HannoZ** [Rzpeg/IdentityServer3.AccessTokenValidation#1]
I have a project that uses a local instance of IdentityServer, so it's not running on https. The IdentityModel Nuget package supports this with an option flag 'RequireHttps' that is set to true by default, but IdentityServer3 exposes no means to set it. 
 I made a small adjustment to the code to make it work, but it would be nicer to have it in the actual Nuget package.

-  add     ` public bool RequireHttps { get; set; } ` to file IdentityServerBearerTokenAuthenticationOptions.cs
- to also have it set to true by default, add to IdentityServerBearerTokenAuthenticationOptions ctor:             `RequireHttps = true; `
- in DiscoveryDocumentIssuerSecurityTokenProvider, change             `var adapteeConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(discoveryEndpoint, new OpenIdConnectConfigurationRetriever(), new HttpClient(handler)) `
to `var adapteeConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(discoveryEndpoint,
                new OpenIdConnectConfigurationRetriever(), new HttpDocumentRetriever(new HttpClient(handler)) { RequireHttps = options.RequireHttps })`

that's all :)

**Comment by Rzpeg** [comment]
Edit: The actual behavior is that it is set to true by default by identitymodel, so I think it's fine.

@HannoZ @PeterButzelaar I don't think we have to require https by default - it will create regression with the actual codebase. The default value should be false.

**Comment by Rzpeg** [comment]
@HannoZ @PeterButzelaar Merged and published as v 4.0.26.
Thanks for the contribution 👍

**Comment by gsvitak** [comment]
Awesome!! thanks.. wish I had this 10 days ago. I wasted a day or so on this issue.
