### ISSUE TITLE
Example of how to use IdentityServer3.AccessTokenValidation with IdentityServer4 for Web API2 .Net Framework 4.61 app

### ISSUE THREAD

**Issue by gsvitak** [Rzpeg/IdentityServer3.AccessTokenValidation#2]
Hello,

Thank you so much for your work on updating this project. It has helped me out and saved me a bunch of time.

I have a .Net Framework 4.61 Web API 2 app that I am trying to secure using IdentityServer4. I saw a post that suggested to use the IdentityServer3.AccessTokenValidation. 

Do you have a sample on how to integrate the Web API project?

Here is what I have done so far

```public void Configuration(IAppBuilder app)
        {
            HttpConfiguration config = new HttpConfiguration();

            config.MapHttpAttributeRoutes();
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "http://localhost:5000",                
                DelayLoadMetadata = true,
                RequiredScopes = new[] { "api1" },
                

                // client credentials for the introspection endpoint
                ClientId = "ro.client",
                ClientSecret = "secret"
            });
           
            app.UseWebApi(config);

```

I am getting the following when I call my API with the Bearer token. I have set the  [Authorize] decorator on the controller.

> IDX20108: The address specified '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]' is not valid as per HTTPS scheme. Please specify an https address for security reasons. If you want to test with http address, set the RequireHttps property &nbsp;on IDocumentRetriever to false.

Thanks in advance for any advice or help.
Greg

**Comment by gsvitak** [comment]
Update. I was able to figure out the issue. For others it is very important to use HTTPS between the Web API service and the IdentityServer. Also make sure you trust the SSL certificate if using IIS Express during development.

**Comment by Rzpeg** [comment]
@gsvitak Hello, 
Thanks for the feedback! The new version  4.0.26 now supports HTTP / HTTPS flags for testing purpose

**Comment by gsvitak** [comment]
Awesome!! thanks.. wish I had this 10 days ago. I wasted a day or so on this issue.
