### ISSUE TITLE
Support IdentityModel 4

### ISSUE THREAD

**Issue by pfeigl** [Rzpeg/IdentityServer3.AccessTokenValidation#6]
IdentityModel 4 has been released about a month ago. As expected, it has some breaking API changes which makes it not work with your fork of IdentityServer3.AccessTokenValidation.

Do you plan to upgrade to IdentityModel 4 or will you stay at version 3?

Thanks,
Philipp

**Comment by Rzpeg** [comment]
@pfeigl 
I saw your pull-request with the update.
I will take a look and then merge it :)

**Comment by Rzpeg** [comment]
@pfeigl Merged

**Comment by Rzpeg** [comment]
@pfeigl Upped AppVeyor environment to VS2019. 
Still cannot compile. WIll publish the package as soon as its fixed

**Comment by Rzpeg** [comment]
@pfeigl published as v 4.1.9

**Comment by Rzpeg** [comment]
@pfeigl 4.1.12 with fixed nuget description
